services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gymbuds
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  server:
    build:
      ./server
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./server:/app/server
    restart: always
    command: npm run start:dev

  web-ui:
    build:
      ./web-ui
    ports:
      - "4200:4200"
    depends_on:
      - server
    volumes:
      - ./graphql:/app/graphql
      - ./web-ui:/app/web-ui
    restart: always
    command: npm start

volumes:
  postgres: